accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', login_required(ActivateView.as_view()), name='activate'),

    path('restore/password/', login_required(RestorePasswordView.as_view()), name='restore_password'),
    path('restore/password/done/', login_required(RestorePasswordDoneView.as_view()), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', login_required(RestorePasswordConfirmView.as_view()), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path

from . import views
# url patterns

urlpatterns = [
    path('', views.user_home, name = 'user_home'),
    path('delete_image/',views.delete_image, name='delete_image'),
    path('update_checkbox/', views.update_checkbox, name='update_checkbox'),
    path('update_approve/', views.update_approve, name = 'update_approve'),
    path('approve_entire_post/', views.approve_entire_post, name='approve_entire_post'),
    path('user_form', views.edit_user_form, name = 'edit_user_form'),
    path('generate_shows/', views.generate_shows, name = 'generate_shows'),
    path('update_appearance', views.update_appearance, name = 'update_appearance')
]

influencer_proj/urls.py
# from dashboard import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url = 'app/')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

accounts/forms.py
from datetime import timedelta

from django import forms
from django.forms import ValidationError
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django.db.models import Q
from django.utils.translation import gettext_lazy as _


class UserCacheMixin:
    user_cache = None


class SignIn(UserCacheMixin, forms.Form):
    password = forms.CharField(label=_('Password'), strip=False, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if settings.USE_REMEMBER_ME:
            self.fields['remember_me'] = forms.BooleanField(label=_('Remember me'), required=False)

    def clean_password(self):
        password = self.cleaned_data['password']

        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You entered an invalid password.'))

        return password


class SignInViaUsernameForm(SignIn):
    username = forms.CharField(label=_('Username'))

    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['username', 'password', 'remember_me']
        return ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']

        user = User.objects.filter(username=username).first()
        if not user:
            raise ValidationError(_('You entered an invalid username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return username


class EmailForm(UserCacheMixin, forms.Form):
    email = forms.EmailField(label=_('Email'))

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email__iexact=email).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return email


class SignInViaEmailForm(SignIn, EmailForm):
    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['email', 'password', 'remember_me']
        return ['email', 'password']


class EmailOrUsernameForm(UserCacheMixin, forms.Form):
    email_or_username = forms.CharField(label=_('Email or Username'))

    def clean_email_or_username(self):
        email_or_username = self.cleaned_data['email_or_username']

        user = User.objects.filter(Q(username=email_or_username) | Q(email__iexact=email_or_username)).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address or username.'))

        if not user.is_active:
            raise ValidationError(_('This account is not active.'))

        self.user_cache = user

        return email_or_username


class SignInViaEmailOrUsernameForm(SignIn, EmailOrUsernameForm):
    @property
    def field_order(self):
        if settings.USE_REMEMBER_ME:
            return ['email_or_username', 'password', 'remember_me']
        return ['email_or_username', 'password']


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = settings.SIGN_UP_FIELDS

    email = forms.EmailField(label=_('Email'), help_text=_('Required. Enter an existing email address.'))

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email__iexact=email).exists()
        if user:
            raise ValidationError(_('You can not use this email address.'))

        return email


class ResendActivationCodeForm(UserCacheMixin, forms.Form):
    email_or_username = forms.CharField(label=_('Email or Username'))

    def clean_email_or_username(self):
        email_or_username = self.cleaned_data['email_or_username']

        user = User.objects.filter(Q(username=email_or_username) | Q(email__iexact=email_or_username)).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address or username.'))

        if user.is_active:
            raise ValidationError(_('This account has already been activated.'))

        activation = user.activation_set.first()
        if not activation:
            raise ValidationError(_('Activation code not found.'))

        now_with_shift = timezone.now() - timedelta(hours=24)
        if activation.created_at > now_with_shift:
            raise ValidationError(_('Activation code has already been sent. You can request a new code in 24 hours.'))

        self.user_cache = user

        return email_or_username


class ResendActivationCodeViaEmailForm(UserCacheMixin, forms.Form):
    email = forms.EmailField(label=_('Email'))

    def clean_email(self):
        email = self.cleaned_data['email']

        user = User.objects.filter(email__iexact=email).first()
        if not user:
            raise ValidationError(_('You entered an invalid email address.'))

        if user.is_active:
            raise ValidationError(_('This account has already been activated.'))

        activation = user.activation_set.first()
        if not activation:
            raise ValidationError(_('Activation code not found.'))

        now_with_shift = timezone.now() - timedelta(hours=24)
        if activation.created_at > now_with_shift:
            raise ValidationError(_('Activation code has already been sent. You can request a new code in 24 hours.'))

        self.user_cache = user

        return email


class RestorePasswordForm(EmailForm):
    pass


class RestorePasswordViaEmailOrUsernameForm(EmailOrUsernameForm):
    pass


class ChangeProfileForm(forms.Form):
    first_name = forms.CharField(label=_('First name'), max_length=30, required=False)
    last_name = forms.CharField(label=_('Last name'), max_length=150, required=False)


class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label=_('Email'))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email']

        if email == self.user.email:
            raise ValidationError(_('Please enter another email.'))

        user = User.objects.filter(Q(email__iexact=email) & ~Q(id=self.user.id)).exists()
        if user:
            raise ValidationError(_('You can not use this mail.'))

        return email


class RemindUsernameForm(EmailForm):
    pass

accounts/templates/accounts/activation-code.html
{% load static %}
{% load bootstrap5 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Log In</title>
    <meta content=""
        name="Empowers DevOps teams to test their websites, web-apps, and APIs with thousands of concurrent connections in real browsers" />

    <meta content="" name="Load Testing, Spike Testing, Stress Testing" />

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
        <a href="https://klona.ai/feed" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
        </a>

        <nav id="navbar" class="navbar">
          <ul>
            <li>
              <a class="nav-link scrollto" href="https://klona.ai/feed">Home</a>
            </li>
<!--            <li>-->
<!--              <a class="nav-link scrollto" href="{% url 'index' %}#about">About</a>-->
<!--            </li>-->
<!--            <li>-->
<!--              <a class="nav-link scrollto" href="{% url 'index' %}#services"-->
<!--                >Services</a-->
<!--              >-->
<!--            </li>-->
<!--            <li>-->
<!--              <a class="nav-link scrollto" href="{% url 'index' %}#contact">Contact</a>-->
<!--            </li>-->
<!--            <li>-->
<!--              <a class="nav-link scrollto" href="{% url 'index' %}#pricing">Pricing</a>-->
<!--            </li>-->
            <li><a class="getstarted scrollto" href="{% url 'accounts:log_in' %}">Log In</a></li>
            <li><a class="getstarted scrollto" href="{% url 'accounts:sign_up' %}">Create Account</a></li>
          </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- .navbar -->
        </div>
    </header>
    <!-- End Header -->
<section id="hero" class="hero d-flex col form-group row gy-4">

    <section class="contact">
        <div class="container" data-aos="fade-up">
            <header class="section-header">
            </header>
        </div>

        <div class="container-fluid mt-3 half">
            <div class="container php-email-form">
                <div class="form-group row gy-4">

            <h2>Resend an activation code</h2>

        
            <form method="post">
                                                      {% csrf_token %}

                <div class="form-group row gy-4">

        
                <input type="hidden">
                <div class="form-group"><label for="id_email_or_username">Email or Username</label><input type="text" name="email_or_username" class="form-control" placeholder="Email or Username" title="" required id="id_email_or_username"></div>
                <div>
                    <button type="submit">Next</button>
                </div>
            </form>
        
            <hr>
                <div>
                    <ul>
                        <li>
                    <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                        </li>
                    </ul>
                </div>
        </div>
        </div>
        </div>
    </section></section>
        
        <script src="{% static 'assets/vendor/jquery/jquery-3.4.1.min.js' %}"></script>

     <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
     <script src="/static/general/js/ie10-viewport-bug-workaround.js"></script>

        <!-- Vendor JS Files -->
        <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--        <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>-->

        <!-- Template Main JS File -->
        <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
        
        </body>
        </html>

accounts/templates/accounts/log_in.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}
 <div class="container">
    <h4>{% trans 'Log in' %}</h4>

            <form class= ".col-md-*" method="post">
    <div class="form-group">
        {% csrf_token %}
       {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Log in' %}</button>
      </div>
    </form>



    <hr>

    <ul>okay
        <li>
            <a href="{% url 'accounts:restore_password' %}">{% trans 'Forgot your password?' %}</a>
        </li>
        <li>
            <a href="{% url 'accounts:remind_username' %}">{% trans 'Forgot your username?' %}</a>
        </li>
        <li>
            <a href="{% url 'accounts:resend_activation_code' %}">{% trans 'Resend an activation code' %}</a>
        </li>
    </ul>
    </div>
{% endblock %}

accounts/templates/accounts/log_out.html
{% extends 'layouts/default/index.html' %}

{% load i18n %}

{% block content %}

    <h4>{% trans 'Logged out' %}</h4>

    <p>
        {% trans 'Thanks for spending some quality time with the site today.' %}
    </p>

    <p>
        <a href="{% url 'accounts:log_in' %}">{% trans 'Log in again' %}</a>
    </p>

{% endblock %}

accounts/templates/accounts/login.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Log In</title>
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
   <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top bg-dark">
      <div
        class="container-fluid container-xl d-flex align-items-center justify-content-between"
      >
        <a href="https://klona.ai/feed" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo-purple-klona.png' %}" alt="" />
        </a>

        <nav id="navbar" class="navbar">
          <ul>
            <li>
              <a class="nav-link scrollto" href="https://klona.ai/feed">Home</a>
            </li>
            <li><a class="getstarted scrollto" href="{% url 'accounts:sign_up' %}">Create Account</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->

<section id="hero2" class="hero2 d-flex col form-group row gy-4">
    <section class="contact">
        <div class="container" data-aos="fade-up">
        </div>
    <div class="container-fluid mt-3 half">
      <div class="container php-email-form">
        <form class=".col-md-*" method="post">
                  {% csrf_token %}

          <div class="form-group row gy-4">
              <img src="{% static 'assets/img/logo-purple-klona.png' %}">
            <h2>Log In</h2>
            <input class="form-control"
              type="hidden"
            />
            <div class="form-group">
              <label for="id_email_or_username">Email or Username</label>
              <input 
                type="text"
                name="email_or_username"
                class="form-control"
                placeholder="Email or Username"
                title=""
                required
                id="id_email_or_username"
              />
            </div>
            <div class="form-group">
              <label for="id_password">Password</label>
              <input 
                type="password"
                name="password"
                class="form-control"
                placeholder="Password"
                title=""
                required
                id="id_password"
              />
            </div>
            <div class="form-group">
              <div class="form-check">
                <input
                  type="checkbox"
                  name="remember_me"
                  class="form-check-input"
                  id="id_remember_me"
                /><label class="form-check-label" for="id_remember_me"
                  >Remember me</label
                >
              </div>
            </div>
            {% for message in messages %}

            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{message}}
                {{ form.errors }}
            </div>
      
            {% endfor %}
              <div>
            <button type="submit">Log in</button>
              </div>
          </div>
        </form>

        <hr />

        <ul>
          <li>
            <a href="{% url 'accounts:restore_password' %}">Forgot your password?</a>
          </li>
        </ul>

      </div>
    </div>

    </section>
    </section>

  <script src="{% static 'assets/vendor/jquery/jquery-3.4.1.min.js' %}"></script>

     <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>

        <!-- Vendor JS Files -->
        <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--        <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>-->

        <!-- Template Main JS File -->
        <script src="{% static 'assets/js/main.js' %}"></script>

  </body>
</html>

accounts/templates/accounts/remind_username.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap5 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Remind a username' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

accounts/templates/accounts/resend_activation_code.html
{% extends 'layouts/default/base.html' %}

{% load bootstrap5 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Resend an activation code' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

accounts/templates/accounts/signup.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>SignUp</title>
    <meta
      content=""
      name="Empowers DevOps teams to test their websites, web-apps, and APIs with thousands of concurrent connections in real browsers"
    />

    <meta content="" name="Load Testing, Spike Testing, Stress Testing" />

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
      <div
        class="container-fluid container-xl d-flex align-items-center justify-content-between"
      >
        <a href="https://klona.ai/feed" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
        </a>

        <nav id="navbar" class="navbar">
          <ul>
            <li>
              <a class="nav-link scrollto" href="https://klona.ai/feed">Home</a>
            </li>
            <li><a class="getstarted scrollto" href="{% url 'accounts:log_in' %}">Log In</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->
<section id="hero2" class="hero2 d-flex col form-group row gy-4">

    <section class="contact">
      <div class="container" data-aos="fade-up">
      </div>

      <div class="container-fluid mt-3 half">
        <div class="container php-email-form">
            {% for message in messages %}

              <div class="alert alert-success">
                  <a class="close" href="#" data-dismiss="alert">×</a>
                      {{ message }}
              </div>

            {% endfor %}


          <form method="post">
                  {% csrf_token %}
            <div class="form-group row gy-4">
              <h2>Create an account</h2>
            <input class="form-control"
              type="hidden"
            />
            <div class="form-group">
              <label for="id_username">Username</label
              ><input 
                type="text"
                name="username"
                maxlength="150"
                autofocus
                class="form-control"
                placeholder="Username"
                title="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
                required
                id="id_username"
              />
              <small class="form-text text-muted"
                >Required. 150 characters or fewer. Letters, digits and
                @/./+/-/_ only.</small
              >
            </div>
            <div class="form-group">
              <label for="id_first_name">First name</label
              ><input
                type="text"
                name="first_name"
                maxlength="150"
                class="form-control"
                placeholder="First name"
                title=""
                id="id_first_name"
              />
            </div>
            <div class="form-group">
              <label for="id_last_name">Last name</label
              ><input
                type="text"
                name="last_name"
                maxlength="150"
                class="form-control"
                placeholder="Last name"
                title=""
                id="id_last_name"
              />
            </div>
            <div class="form-group">
              <label for="id_email">Email</label
              ><input
                type="email"
                name="email"
                class="form-control"
                placeholder="Email"
                title="Required. Enter an existing email address."
                required
                id="id_email"
              />
              <small class="form-text text-muted"
                >Required. Enter an existing email address.</small
              >
            </div>
            <div class="form-group">
              <label for="id_password1">Password</label
              ><input
                type="password"
                name="password1"
                autocomplete="new-password"
                class="form-control"
                placeholder="Password"
                title="Your password can’t be too similar to your other personal information.Your password must contain at least 8 characters.Your password can’t be a commonly used password.Your password can’t be entirely numeric."
                required
                id="id_password1"
              />
              <small class="form-text text-muted">
                <ul>
                  <li>
                    Your password can’t be too similar to your other personal
                    information.
                  </li>
                  <li>Your password must contain at least 8 characters.</li>
                  <li>Your password can’t be a commonly used password.</li>
                  <li>Your password can’t be entirely numeric.</li>
                </ul>
              </small>
            </div>
            <div class="form-group">
              <label for="id_password2">Password confirmation</label
              ><input
                type="password"
                name="password2"
                autocomplete="new-password"
                class="form-control"
                placeholder="Password confirmation"
                title="Enter the same password as before, for verification."
                required
                id="id_password2"
              />
              <small class="form-text text-muted"
                >Enter the same password as before, for verification.</small
              >
            </div>
            <div>
            <button type="submit">Create</button>
            </div>
            </div>
          </form>
        </div>
      </div>
      </div>
    </section>
</section>


    <script src="{% static 'assets/vendor/jquery/jquery-3.4.1.min.js' %}"></script>

     <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="/static/general/vendor/popper/popper.min.js"></script>

    <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>

    <!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>-->

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>