accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', login_required(ActivateView.as_view()), name='activate'),

    path('restore/password/', login_required(RestorePasswordView.as_view()), name='restore_password'),
    path('restore/password/done/', login_required(RestorePasswordDoneView.as_view()), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', login_required(RestorePasswordConfirmView.as_view()), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path

from . import views
# url patterns

urlpatterns = [
    path('', views.user_home, name = 'user_home'),
    path('delete_image/',views.delete_image, name='delete_image'),
    path('update_checkbox/', views.update_checkbox, name='update_checkbox'),
    path('update_approve/', views.update_approve, name = 'update_approve'),
    path('approve_entire_post/', views.approve_entire_post, name='approve_entire_post'),
    path('user_form', views.edit_user_form, name = 'edit_user_form'),
    path('generate_shows/', views.generate_shows, name = 'generate_shows'),
    path('update_appearance', views.update_appearance, name = 'update_appearance')
]

influencer_proj/urls.py
# from dashboard import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url = 'app/')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME, update_session_auth_hash
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme as is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings
from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation


class GuestOnlyView(View):

    def dispatch(self, request, *args, **kwargs):
        # Delete Existing Messages.
        storage = messages.get_messages(request)
        for _ in storage:
            # Without this loop `_loaded_messages` is empty
            pass
        for _ in list(storage._loaded_messages):
            del storage._loaded_messages[0]
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if not user and password:
            messages.error(request, 'Incorrect Username or Password. Try Again')

        if request.session.get('SignUp_done'):
            print('DONE')
            messages.success(request, 'You have signed up. To activate the account, contact the admin.')

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/login.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # if request.session.get('SignUp_done'):
        #     request.session['SignUp_done'] = ''
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()
        if 'SignUp_done' in request.session.keys():
            del request.session['SignUp_done']


        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request
        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)
        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME)
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return super().dispatch(request)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/signup.html'
    form_class = SignUpForm

    def form_invalid(self, form):

        return redirect('accounts:sign_up')

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        # user_table.create_collection_master_table_for_user()
        # user_table.create_collection_result_detail_for_user()
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()


            messages.success(
                request, 'You are signed up. To activate the account, contact the admin.')
            request.session['SignUp_done'] = 'yes'
            # return redirect('signup')
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('You are successfully signed up!'))

        return redirect('accounts:sign_up')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/activation-code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        if isinstance(uid, bytes):
            uid = uid.decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):

accounts/templates/layouts/default/page.html
{% load static %}
{% load bootstrap5 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Klona</title>
    <meta content="" name="Empowers DevOps teams to test their websites, web-apps, and APIs with thousands of concurrent connections in real browsers" />

    <meta content="" name="Load Testing, Spike Testing, Stress Testing" />

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <!-- Custom css -->
    <link href="{% static 'runtest/css/runtest.css' %}" rel="stylesheet" />
     
</head>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
      <div
        class="container-fluid container-xl d-flex justify-content-between"
      >
        <a href="https://klona.ai/feed" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
        </a>

        <nav id="navbar" class="navbar navbar-light" style="background-color: #0000;">
          <ul>
            {% if request.user.is_authenticated %}
            <li><a class="nav-link scrollto active" href="{% url 'dashboard' %}">Dashboard</a></li>
            <li><a class="nav-link scrollto active" href="{% url 'page' %}">Run Tests</a></li>
            {% else %}
            <li><a class="nav-link scrollto " href="{% url 'index' %}">Home</a></li>
            {% endif %}
           {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                <li><a class="nav-link scrollto" href="{% url 'admin:login' %}">{% trans 'Admin' %}</a></li>
            {% endif %}
                <li><a class="nav-link scrollto "  href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a></li>
                <li><a class="nav-link scrollto " href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a></li>
                <li><a class="nav-link scrollto " href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a></li>
                <li><a class="nav-link scrollto " href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a></li>
            {% else %}
                <li><a class="nav-link scrollto active" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a></li>
                <li><a class="nav-link scrollto active" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a></li>
            {% endif %}
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->

    {% if request.user.is_authenticated and request.path == '/runtests' and request.method != 'POST' %}
        <!-- ======= Hero Section ======= -->

<section id="hero" class="hero d-flex col form-group row gy-4">
    <section class="contact">
        <div class="container" data-aos="fade-up">
            <header class="section-header">
            </header>
        </div>
        <div class="container-fluid mt-3 half">
            <div class="container php-email-form">
                <div class="form-group row gy-4">
                <form class=".col-md-*" method="POST">
                    {% csrf_token %}
                    <div class="form-group row gy-4">
                        <input type="hidden">
                        <label class="form-check-label">
                            <h3>Select the Platform for Test</h3>
                        </label>
                    </div>
                    <div class="form-check gy-4">
                        <input class="form-check-input" onclick="show_urls()" type="radio" name="flexRadioDefault"
                            id="flexRadioDefault1">
                        <label class="form-check-label" for="flexRadioDefault1">
                            Test Website
                        </label>
                    </div>
                    <div class="form-check gy-4">
                        <input class="form-check-input" onclick="show_postman_collection()" type="radio"
                            name="flexRadioDefault" id="flexRadioDefault2">
                        <label class="form-check-label" for="flexRadioDefault2">
                            Test Postman Collection
                        </label>
                    </div> <hr/>
                    <div class="container-fluid mt-3 col-lg-12 text-center" id="urls">
                        <div class="col-lg-12 text-center php-email-form">
                            <div class="card-header col-lg-12 text-center">
                                <h4>Insert URL</h4>
                            </div>
                            <div class="card-block form-group">
                                <br>
                                <form method="get" class="dropzone dz-clickable col-lg-12 text-center form-control">
                                  <!-- {% csrf_token %} -->
                                    <input type="url" name="url" class="form-control" required>
                                    <br>
                                    <div class=".col-md-* text-center">
                                        <a href="/performtest/"></a><button type="submit"
                                                class="btn btn-outline-success" onclick="load_spinner_url()"><strong>Check</strong></button>
                                    </div>
                                </form>
                                <span>Note: Please Specify the Protocol in Your URL. E.G. http:// or https://</span>
                            </div>

                        </div>
                    </div>

                    <div class="container-fluid mt-3 col-lg-12" id="postman_collection">
                        <div class="col-lg-12 php-email-form">
                            <div class="card-header col-12 text-center">
                                <h4>Upload Postman Collection</h4>
                            </div>
                            <div class="card-block form-group">
                                <form method="post" enctype="multipart/form-data" class="dropzone dz-clickable row-lg-12 text-center">
                                                                                              {% csrf_token %}

                                    <input type="hidden">
                                    <input accept=".json" required type="file" name="uploadedfile">
                                    <div class=".col-md-* text-center">
                                        <br>
                                        <button type="submit" name="upload_collection" onclick="load_spinner_col()"
                                        class="btn btn-outline-success">
                                            <strong>Verify</strong>
                                        </button>
                                    </div>
                                </form>
                                
                            </div>
                            <br>
                            <p class="text-xl-left text-muted h6">
                                1. Authentication is not supported at present
                                <br>
                                2. Only Raw and x-www-form-url-encoded body type is supported
                                <br>
                                3. Check if collection has tests, Tests are not supported
                                <br>
                                4. Collection version is 2.1 is supported, old ones are not suppported
                            </p>
                        </div>
                    </div>
            </form>
        </div>
            
        </div>
<div class="spanner ">
  <div class="loader"></div>
  <p>Processing Your Request... Please be patient.</p>
</div>
        </div>

    </section>
</section>
    <!-- End Hero -->


{% endif %}


    <!-- End Hero -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>
        <script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/vendor/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<!--    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>-->

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  <!-- Display the urls/postman -->
  <script>

    url = document.getElementById('urls')
    collection_run = document.getElementById('postman_collection')
    if(collection_run){
        collection_run.style.display = "none";
    }
    if (url){
        url.style.display = "none";
    }
    function show_postman_collection(){
           document.getElementById('postman_collection').style.display = "block";
           document.getElementById('urls').style.display = "none";
    }
    function show_urls(){
        document.getElementById('urls').style.display = "block";
        document.getElementById('postman_collection').style.display = "none";
    }
  function load_spinner_url(){
    if(url){
        var inputUrl = document.getElementsByName('url')[0];
        var report = inputUrl.reportValidity()
        if (report){
            document.getElementsByClassName("spanner")[0].classList.add("show");
        }
    }
  };
  function load_spinner_col(){

        if (collection_run){
            var inputCol = document.getElementsByName('uploadedfile')[0];
            var report = inputCol.reportValidity()
            if (report){
                document.getElementsByClassName("spanner")[0].classList.add("show");
            }
        }
  };

</script>

  </body>
</html>